version: '3.9'

services:
  db:
    container_name: chintai_database
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data:rw

  pgadmin:
    container_name: chintai_pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - 8080:80
    depends_on:
      - db
